__Numpy ndarray__

In [3]:
import numpy as np

In [5]:
data = [[ 2, 6, 1, 3, 7],
        [5, 10, 4, 9, 8]]

data = np.array(data)

data

array([[ 2,  6,  1,  3,  7],
       [ 5, 10,  4,  9,  8]])

In [6]:
(data.shape)

(2, 5)

In [7]:
(np.zeros((2,3)))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
(np.ones((2,3)))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
array = np.arange(10)
(array)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
(array[2:5])

array([2, 3, 4])

In [11]:
array[5:8] = 0
(array)

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

__Array Operations__

In [12]:
data = np.array([[5,6,7],
                [8,9,10]])
(data+5)

array([[10, 11, 12],
       [13, 14, 15]])

In [13]:
(data-3)

array([[2, 3, 4],
       [5, 6, 7]])

In [14]:
data = np.arange(16).reshape((4,4))
(data)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
(data.T)

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [16]:
x = np.random.randn(2,3)
(x)

array([[ 0.39533942,  0.53552588,  1.14244375],
       [-1.41191552, -0.21259387,  2.6734031 ]])

__Statistical Methods__

In [19]:
data = np.random.randn(3,2)
data

array([[-0.32724336, -0.28325206],
       [ 0.84202954, -0.22453151],
       [-0.50715362,  0.21516856]])

In [20]:
data.mean()

-0.04749707426964028

In [21]:
data.min()

-0.5071536171509013

In [22]:
data.max()

0.8420295431053584

__Matrix Class__

In [23]:
X = np.random.randn(3,2)
X = np.matrix(X)
X

matrix([[ 0.63786334, -1.36596181],
        [ 0.38892094, -1.52545061],
        [-1.16846476, -0.83611762]])

In [24]:
Y = np.random.randn(2,2)
Y = np.matrix(Y)
Y

matrix([[ 1.67528805e-03, -8.27702329e-01],
        [-1.39119743e+00,  3.28136978e+00]])

In [25]:
X*Y

matrix([[ 1.90139117, -5.01018679],
        [ 2.12285453, -5.32747829],
        [ 1.16124718, -1.7764701 ]])