__Numpy ndarray__

In [4]:
import numpy as np

In [38]:
data = [[ 2, 6, 1, 3, 7],
        [5, 10, 4, 9, 8]]

data = np.array(data)

(data)

array([[ 2,  6,  1,  3,  7],
       [ 5, 10,  4,  9,  8]])

In [37]:
(data.shape)

(2, 3)

In [36]:
(np.zeros((2,3)))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
(np.ones((2,3)))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
array = np.arange(10)
(array)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
(array[2:5])

array([2, 3, 4])

In [32]:
array[5:8] = 0
(array)

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

__Array Operations__

In [31]:
data = np.array([[5,6,7],
                [8,9,10]])
(data+5)

array([[10, 11, 12],
       [13, 14, 15]])

In [30]:
(data-3)

array([[-3, -2, -1,  0],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
data = np.arange(16).reshape((4,4))
(data)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
(data.T)

array([[ 2,  5],
       [ 6, 10],
       [ 1,  4],
       [ 3,  9],
       [ 7,  8]])

In [40]:
x = np.random.randn(2,3)
(x)

array([[ 0.0567582 ,  0.07823287, -0.10911688],
       [ 0.2956842 , -0.01416633, -1.29642707]])

__Statistical Methods__

In [41]:
data = np.random.randn(3,2)

In [42]:
data.mean()

0.5380994398271395

In [43]:
data.min()

-1.3020044424100339

In [44]:
data.max()

2.7787208228323546

__Matrix Class__

In [53]:
X = np.random.randn(3,2)
X = np.matrix(X)
X

matrix([[ 0.18893845, -1.88961662],
        [-0.4030279 ,  0.08735951],
        [-1.78739063, -0.82044257]])

In [54]:
Y = np.random.randn(2,2)
Y = np.matrix(Y)
Y

matrix([[-0.08098866, -0.38003117],
        [ 0.36324828, -1.72088537]])

In [56]:
X*Y

matrix([[-7.01701855e-01,  3.18001111e+00],
        [ 6.43738821e-02,  2.82746758e-03],
        [-1.53265968e-01,  2.09115177e+00]])